<a href="https://colab.research.google.com/github/PalakDograCSE-AI2004/CVDL_Summer_Internship/blob/main/Simple_ANN_from_scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
x=np.array([
    [1,0,1,0],
    [1,0,1,1],
    [0,1,0,1]])
y=np.array([[1],[1],[0]])

In [ ]:
x

array([[1, 0, 1, 0],
       [1, 0, 1, 1],
       [0, 1, 0, 1]])

In [ ]:
y

array([[1],
       [1],
       [0]])

In [ ]:
#defining activation function
def sigmoid(x):
  return 1/(1+np.exp(-x))

In [ ]:
x.shape

(3, 4)

In [ ]:
y.shape

(3, 1)

In [ ]:
#input layer neurons will always be equal to the number of columns
inputNeurons=x.shape[1]
#hidden neurons are decided by hit and trial method
hiddenNeurons=4
#outputNeurons depends on number of classes in traget column
outputNeurons=1

In [ ]:
weightsHidden=np.random.uniform(size=(inputNeurons,hiddenNeurons))
biasHidden=np.random.uniform(size=(1,hiddenNeurons))
weightsOutput=np.random.uniform(size=(hiddenNeurons,outputNeurons))
biasOutput=np.random.uniform(size=(1,outputNeurons))


In [ ]:
#feedForward
fx=np.dot(x,weightsHidden)+biasHidden
hiddenLayer=sigmoid(fx)
hiddenLayer

array([[0.79237038, 0.82469927, 0.69827025, 0.81952787],
       [0.86704463, 0.92247156, 0.7445319 , 0.88603793],
       [0.8158695 , 0.79857443, 0.64352705, 0.84415484]])

In [ ]:
fx_=np.dot(hiddenLayer,weightsOutput)+biasOutput

In [ ]:
outputLayer=sigmoid(fx_)
outputLayer
#this is our prediction ie y cap

array([[0.76372398],
       [0.78057474],
       [0.76513921]])

In [ ]:
#backPropogation
def derivativeSigmoid(x):
  return x*(1-x)

In [ ]:
#backPropogation

#on output layer
errorOutput=outputLayer-y
slopeOutput=derivativeSigmoid(outputLayer)
deltaOutput=errorOutput*slopeOutput

#now apply same steps on hidden layer
errorHidden=np.dot(deltaOutput,weightsOutput.T)
slopeHidden=derivativeSigmoid(hiddenLayer)
deltaHidden=errorHidden*slopeHidden


In [ ]:
errorOutput

array([[-0.23627602],
       [-0.21942526],
       [ 0.76513921]])

In [ ]:
#now loss is found (errorOutput). Now we will optimize it

In [ ]:
#optimizing weights

alpha=0.01
#updating Weightoutput
weightsOutput=weightsOutput-hiddenLayer.T.dot(deltaOutput)*alpha
#updating Weighthidden
weightsHidden=weightsHidden-x.T.dot(deltaHidden)*alpha
#updating biasoutput
biasOutput=biasOutput-np.sum(deltaOutput)*alpha
#updating biashidden
biasHidden=biasHidden-np.sum(deltaHidden)*alpha

In [ ]:
#combine all and put into iteration(by variable EPOCH)
import numpy as np
x=np.array([
    [1,0,1,0],
    [1,0,1,1],
    [0,1,0,1]])
y=np.array([[1],[1],[0]])
#defining activation function
def sigmoid(x):
  return 1/(1+np.exp(-x))
#input layer neurons will always be equal to the number of columns
inputNeurons=x.shape[1]
#hidden neurons are decided by hit and trial method
hiddenNeurons=4
#outputNeurons depends on number of classes in traget column
outputNeurons=1

weightsHidden=np.random.uniform(size=(inputNeurons,hiddenNeurons))
biasHidden=np.random.uniform(size=(1,hiddenNeurons))
weightsOutput=np.random.uniform(size=(hiddenNeurons,outputNeurons))
biasOutput=np.random.uniform(size=(1,outputNeurons))

alpha=0.01
EPOCH=90000
for i in range(EPOCH):
  #feedForward
  fx=np.dot(x,weightsHidden)+biasHidden
  hiddenLayer=sigmoid(fx)
  fx_=np.dot(hiddenLayer,weightsOutput)+biasOutput
  outputLayer=sigmoid(fx_)
  #backPropogation
  def derivativeSigmoid(x):
    return x*(1-x)
  #backPropogation

  #on output layer
  errorOutput=outputLayer-y
  slopeOutput=derivativeSigmoid(outputLayer)
  deltaOutput=errorOutput*slopeOutput

  #now apply same steps on hidden layer
  errorHidden=np.dot(deltaOutput,weightsOutput.T)
  slopeHidden=derivativeSigmoid(hiddenLayer)
  deltaHidden=errorHidden*slopeHidden
  #optimizing weights


  #updating Weightoutput
  weightsOutput=weightsOutput-hiddenLayer.T.dot(deltaOutput)*alpha
  #updating Weighthidden
  weightsHidden=weightsHidden-x.T.dot(deltaHidden)*alpha
  #updating biasoutput
  biasOutput=biasOutput-np.sum(deltaOutput)*alpha
  #updating biashidden
  biasHidden=biasHidden-np.sum(deltaHidden)*alpha

In [ ]:
outputLayer

array([[0.98464109],
       [0.97841695],
       [0.0278804 ]])